### PR TITLE
Line change needed for other resoltions

### PR DESCRIPTION
**Pull request by markbirss**
these 2 lines need to be changed for your specific e-paper resolution
line 23
and 
line 113

### CODE REVIEW

**Comment by amadeok** [comment]
Hi thanks for pointing it out. In fact line 113 is not necessary, i just forgot to remove it. We can safely delete that line

**Comment by markbirss** [comment]
@amadeok  but my screen did not draw correctly until i changed both ? LilyGo 4.7 960x540, because the values was diffirent. But you saying i just need to set it once, i guess

**Comment by amadeok** [comment]
Because the second line overwrites the first one. If we just delete the
second one the values of line 23 will be used.

Il giorno dom 21 feb 2021 alle ore 16:24 Mark Trevor Birss <
notifications@github.com> ha scritto:

**Comment by amadeok** [comment]
I already deleted line 113 from the code, you can do the same.

Il giorno dom 21 feb 2021 alle ore 16:25 Cristian Jorge A. Kusch <
amadeokusch@gmail.com> ha scritto:

**Pull request closed without merging**
